# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35tfgg484-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir F:/FPGA_VIVADO/PCIe_ep/PCIE_EP.cache/wt [current_project]
set_property parent.project_path F:/FPGA_VIVADO/PCIe_ep/PCIE_EP.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo f:/FPGA_VIVADO/PCIe_ep/PCIE_EP.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog {
  F:/FPGA_VIVADO/PCIe_ep/PCIE_EP.srcs/sources_1/design/xilinx.vh
  F:/FPGA_VIVADO/PCIe_ep/PCIE_EP.srcs/sources_1/design/widths.vh
  F:/FPGA_VIVADO/PCIe_ep/PCIE_EP.srcs/sources_1/design/types.vh
  F:/FPGA_VIVADO/PCIe_ep/PCIE_EP.srcs/sources_1/design/ultrascale.vh
  F:/FPGA_VIVADO/PCIe_ep/PCIE_EP.srcs/sources_1/design/functions.vh
  F:/FPGA_VIVADO/PCIe_ep/PCIE_EP.srcs/sources_1/design/trellis.vh
  F:/FPGA_VIVADO/PCIe_ep/PCIE_EP.srcs/sources_1/design/tlp.vh
  F:/FPGA_VIVADO/PCIe_ep/PCIE_EP.srcs/sources_1/design/riffa.vh
  F:/FPGA_VIVADO/PCIe_ep/PCIE_EP.srcs/sources_1/design/schedules.vh
}
set_property is_global_include true [get_files F:/FPGA_VIVADO/PCIe_ep/PCIE_EP.srcs/sources_1/design/xilinx.vh]
set_property is_global_include true [get_files F:/FPGA_VIVADO/PCIe_ep/PCIE_EP.srcs/sources_1/design/widths.vh]
set_property is_global_include true [get_files F:/FPGA_VIVADO/PCIe_ep/PCIE_EP.srcs/sources_1/design/types.vh]
set_property is_global_include true [get_files F:/FPGA_VIVADO/PCIe_ep/PCIE_EP.srcs/sources_1/design/ultrascale.vh]
set_property is_global_include true [get_files F:/FPGA_VIVADO/PCIe_ep/PCIE_EP.srcs/sources_1/design/functions.vh]
set_property is_global_include true [get_files F:/FPGA_VIVADO/PCIe_ep/PCIE_EP.srcs/sources_1/design/trellis.vh]
set_property is_global_include true [get_files F:/FPGA_VIVADO/PCIe_ep/PCIE_EP.srcs/sources_1/design/tlp.vh]
set_property is_global_include true [get_files F:/FPGA_VIVADO/PCIe_ep/PCIE_EP.srcs/sources_1/design/riffa.vh]
read_verilog -library xil_defaultlib {
  F:/FPGA_VIVADO/PCIe_ep/PCIE_EP.srcs/sources_1/design/async_fifo.v
  F:/FPGA_VIVADO/PCIe_ep/PCIE_EP.srcs/sources_1/design/async_fifo_fwft.v
  F:/FPGA_VIVADO/PCIe_ep/PCIE_EP.srcs/sources_1/design/channel.v
  F:/FPGA_VIVADO/PCIe_ep/PCIE_EP.srcs/sources_1/design/channel_128.v
  F:/FPGA_VIVADO/PCIe_ep/PCIE_EP.srcs/sources_1/design/channel_32.v
  F:/FPGA_VIVADO/PCIe_ep/PCIE_EP.srcs/sources_1/design/channel_64.v
  F:/FPGA_VIVADO/PCIe_ep/PCIE_EP.srcs/sources_1/design/chnl_tester.v
  F:/FPGA_VIVADO/PCIe_ep/PCIE_EP.srcs/sources_1/design/counter.v
  F:/FPGA_VIVADO/PCIe_ep/PCIE_EP.srcs/sources_1/design/cross_domain_signal.v
  F:/FPGA_VIVADO/PCIe_ep/PCIE_EP.srcs/sources_1/design/demux.v
  F:/FPGA_VIVADO/PCIe_ep/PCIE_EP.srcs/sources_1/design/engine_layer.v
  F:/FPGA_VIVADO/PCIe_ep/PCIE_EP.srcs/sources_1/design/ff.v
  F:/FPGA_VIVADO/PCIe_ep/PCIE_EP.srcs/sources_1/design/fifo.v
  F:/FPGA_VIVADO/PCIe_ep/PCIE_EP.srcs/sources_1/design/fifo_packer_128.v
  F:/FPGA_VIVADO/PCIe_ep/PCIE_EP.srcs/sources_1/design/fifo_packer_32.v
  F:/FPGA_VIVADO/PCIe_ep/PCIE_EP.srcs/sources_1/design/fifo_packer_64.v
  F:/FPGA_VIVADO/PCIe_ep/PCIE_EP.srcs/sources_1/design/interrupt.v
  F:/FPGA_VIVADO/PCIe_ep/PCIE_EP.srcs/sources_1/design/interrupt_controller.v
  F:/FPGA_VIVADO/PCIe_ep/PCIE_EP.srcs/sources_1/design/mux.v
  F:/FPGA_VIVADO/PCIe_ep/PCIE_EP.srcs/sources_1/design/offset_flag_to_one_hot.v
  F:/FPGA_VIVADO/PCIe_ep/PCIE_EP.srcs/sources_1/design/offset_to_mask.v
  F:/FPGA_VIVADO/PCIe_ep/PCIE_EP.srcs/sources_1/design/one_hot_mux.v
  F:/FPGA_VIVADO/PCIe_ep/PCIE_EP.srcs/sources_1/design/pipeline.v
  F:/FPGA_VIVADO/PCIe_ep/PCIE_EP.srcs/sources_1/design/ram_1clk_1w_1r.v
  F:/FPGA_VIVADO/PCIe_ep/PCIE_EP.srcs/sources_1/design/ram_2clk_1w_1r.v
  F:/FPGA_VIVADO/PCIe_ep/PCIE_EP.srcs/sources_1/design/recv_credit_flow_ctrl.v
  F:/FPGA_VIVADO/PCIe_ep/PCIE_EP.srcs/sources_1/design/register.v
  F:/FPGA_VIVADO/PCIe_ep/PCIE_EP.srcs/sources_1/design/registers.v
  F:/FPGA_VIVADO/PCIe_ep/PCIE_EP.srcs/sources_1/design/reorder_queue.v
  F:/FPGA_VIVADO/PCIe_ep/PCIE_EP.srcs/sources_1/design/reorder_queue_input.v
  F:/FPGA_VIVADO/PCIe_ep/PCIE_EP.srcs/sources_1/design/reorder_queue_output.v
  F:/FPGA_VIVADO/PCIe_ep/PCIE_EP.srcs/sources_1/design/reset_controller.v
  F:/FPGA_VIVADO/PCIe_ep/PCIE_EP.srcs/sources_1/design/reset_extender.v
  F:/FPGA_VIVADO/PCIe_ep/PCIE_EP.srcs/sources_1/design/riffa.v
  F:/FPGA_VIVADO/PCIe_ep/PCIE_EP.srcs/sources_1/design/riffa_wrapper_ac701.v
  F:/FPGA_VIVADO/PCIe_ep/PCIE_EP.srcs/sources_1/design/rotate.v
  F:/FPGA_VIVADO/PCIe_ep/PCIE_EP.srcs/sources_1/design/rx_engine_classic.v
  F:/FPGA_VIVADO/PCIe_ep/PCIE_EP.srcs/sources_1/design/rx_engine_ultrascale.v
  F:/FPGA_VIVADO/PCIe_ep/PCIE_EP.srcs/sources_1/design/rx_port_128.v
  F:/FPGA_VIVADO/PCIe_ep/PCIE_EP.srcs/sources_1/design/rx_port_32.v
  F:/FPGA_VIVADO/PCIe_ep/PCIE_EP.srcs/sources_1/design/rx_port_64.v
  F:/FPGA_VIVADO/PCIe_ep/PCIE_EP.srcs/sources_1/design/rx_port_channel_gate.v
  F:/FPGA_VIVADO/PCIe_ep/PCIE_EP.srcs/sources_1/design/rx_port_reader.v
  F:/FPGA_VIVADO/PCIe_ep/PCIE_EP.srcs/sources_1/design/rx_port_requester_mux.v
  F:/FPGA_VIVADO/PCIe_ep/PCIE_EP.srcs/sources_1/design/rxc_engine_128.v
  F:/FPGA_VIVADO/PCIe_ep/PCIE_EP.srcs/sources_1/design/rxc_engine_classic.v
  F:/FPGA_VIVADO/PCIe_ep/PCIE_EP.srcs/sources_1/design/rxc_engine_ultrascale.v
  F:/FPGA_VIVADO/PCIe_ep/PCIE_EP.srcs/sources_1/design/rxr_engine_128.v
  F:/FPGA_VIVADO/PCIe_ep/PCIE_EP.srcs/sources_1/design/rxr_engine_classic.v
  F:/FPGA_VIVADO/PCIe_ep/PCIE_EP.srcs/sources_1/design/rxr_engine_ultrascale.v
  F:/FPGA_VIVADO/PCIe_ep/PCIE_EP.srcs/sources_1/design/scsdpram.v
  F:/FPGA_VIVADO/PCIe_ep/PCIE_EP.srcs/sources_1/design/sg_list_reader_128.v
  F:/FPGA_VIVADO/PCIe_ep/PCIE_EP.srcs/sources_1/design/sg_list_reader_32.v
  F:/FPGA_VIVADO/PCIe_ep/PCIE_EP.srcs/sources_1/design/sg_list_reader_64.v
  F:/FPGA_VIVADO/PCIe_ep/PCIE_EP.srcs/sources_1/design/sg_list_requester.v
  F:/FPGA_VIVADO/PCIe_ep/PCIE_EP.srcs/sources_1/design/shiftreg.v
  F:/FPGA_VIVADO/PCIe_ep/PCIE_EP.srcs/sources_1/design/sync_fifo.v
  F:/FPGA_VIVADO/PCIe_ep/PCIE_EP.srcs/sources_1/design/syncff.v
  F:/FPGA_VIVADO/PCIe_ep/PCIE_EP.srcs/sources_1/design/translation_xilinx.v
  F:/FPGA_VIVADO/PCIe_ep/PCIE_EP.srcs/sources_1/design/tx_alignment_pipeline.v
  F:/FPGA_VIVADO/PCIe_ep/PCIE_EP.srcs/sources_1/design/tx_data_fifo.v
  F:/FPGA_VIVADO/PCIe_ep/PCIE_EP.srcs/sources_1/design/tx_data_pipeline.v
  F:/FPGA_VIVADO/PCIe_ep/PCIE_EP.srcs/sources_1/design/tx_data_shift.v
  F:/FPGA_VIVADO/PCIe_ep/PCIE_EP.srcs/sources_1/design/tx_engine.v
  F:/FPGA_VIVADO/PCIe_ep/PCIE_EP.srcs/sources_1/design/tx_engine_classic.v
  F:/FPGA_VIVADO/PCIe_ep/PCIE_EP.srcs/sources_1/design/tx_engine_selector.v
  F:/FPGA_VIVADO/PCIe_ep/PCIE_EP.srcs/sources_1/design/tx_engine_ultrascale.v
  F:/FPGA_VIVADO/PCIe_ep/PCIE_EP.srcs/sources_1/design/tx_hdr_fifo.v
  F:/FPGA_VIVADO/PCIe_ep/PCIE_EP.srcs/sources_1/design/tx_multiplexer.v
  F:/FPGA_VIVADO/PCIe_ep/PCIE_EP.srcs/sources_1/design/tx_multiplexer_128.v
  F:/FPGA_VIVADO/PCIe_ep/PCIE_EP.srcs/sources_1/design/tx_multiplexer_32.v
  F:/FPGA_VIVADO/PCIe_ep/PCIE_EP.srcs/sources_1/design/tx_multiplexer_64.v
  F:/FPGA_VIVADO/PCIe_ep/PCIE_EP.srcs/sources_1/design/tx_port_128.v
  F:/FPGA_VIVADO/PCIe_ep/PCIE_EP.srcs/sources_1/design/tx_port_32.v
  F:/FPGA_VIVADO/PCIe_ep/PCIE_EP.srcs/sources_1/design/tx_port_64.v
  F:/FPGA_VIVADO/PCIe_ep/PCIE_EP.srcs/sources_1/design/tx_port_buffer_128.v
  F:/FPGA_VIVADO/PCIe_ep/PCIE_EP.srcs/sources_1/design/tx_port_buffer_32.v
  F:/FPGA_VIVADO/PCIe_ep/PCIE_EP.srcs/sources_1/design/tx_port_buffer_64.v
  F:/FPGA_VIVADO/PCIe_ep/PCIE_EP.srcs/sources_1/design/tx_port_channel_gate_128.v
  F:/FPGA_VIVADO/PCIe_ep/PCIE_EP.srcs/sources_1/design/tx_port_channel_gate_32.v
  F:/FPGA_VIVADO/PCIe_ep/PCIE_EP.srcs/sources_1/design/tx_port_channel_gate_64.v
  F:/FPGA_VIVADO/PCIe_ep/PCIE_EP.srcs/sources_1/design/tx_port_monitor_128.v
  F:/FPGA_VIVADO/PCIe_ep/PCIE_EP.srcs/sources_1/design/tx_port_monitor_32.v
  F:/FPGA_VIVADO/PCIe_ep/PCIE_EP.srcs/sources_1/design/tx_port_monitor_64.v
  F:/FPGA_VIVADO/PCIe_ep/PCIE_EP.srcs/sources_1/design/tx_port_writer.v
  F:/FPGA_VIVADO/PCIe_ep/PCIE_EP.srcs/sources_1/design/txc_engine_classic.v
  F:/FPGA_VIVADO/PCIe_ep/PCIE_EP.srcs/sources_1/design/txc_engine_ultrascale.v
  F:/FPGA_VIVADO/PCIe_ep/PCIE_EP.srcs/sources_1/design/txr_engine_classic.v
  F:/FPGA_VIVADO/PCIe_ep/PCIE_EP.srcs/sources_1/design/txr_engine_ultrascale.v
  F:/FPGA_VIVADO/PCIe_ep/PCIE_EP.srcs/sources_1/design/AC701_Gen1x4If64.v
}
read_ip -quiet f:/FPGA_VIVADO/PCIe_ep/PCIE_EP.srcs/sources_1/ip/pcie_7x_0/pcie_7x_0.xci
set_property used_in_implementation false [get_files -all f:/FPGA_VIVADO/PCIe_ep/PCIE_EP.srcs/sources_1/ip/pcie_7x_0/source/pcie_7x_0-PCIE_X0Y0.xdc]
set_property used_in_implementation false [get_files -all f:/FPGA_VIVADO/PCIe_ep/PCIE_EP.srcs/sources_1/ip/pcie_7x_0/synth/pcie_7x_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc F:/FPGA_VIVADO/PCIe_ep/PCIE_EP.srcs/constrs_1/pcie_pin.xdc
set_property used_in_implementation false [get_files F:/FPGA_VIVADO/PCIe_ep/PCIE_EP.srcs/constrs_1/pcie_pin.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top AC701_Gen1x4If64 -part xc7a35tfgg484-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef AC701_Gen1x4If64.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file AC701_Gen1x4If64_utilization_synth.rpt -pb AC701_Gen1x4If64_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
